# SPDX-FileCopyrightText: : 2021 The PyPSA-Africa Authors
#
# SPDX-License-Identifier: CC0-1.0

version: 0.3.0
tutorial: False

logging:
  level: INFO
  format: "%(levelname)s:%(name)s:%(message)s"

scenario:
  simpl: ['']
  ll: ['copt']
  clusters: [6]
  opts: [Co2L-3H]

countries: ["africa"]
# Can be replaced by country ["NG", "BJ"] or user specific region, more at https://pypsa-meets-africa.readthedocs.io/en/latest/configuration.html#top-level-configuration

summary_dir: results

snapshots:
  start: "2013-01-01"
  end: "2014-01-01"
  closed: "left" # end is not inclusive

enable:
  retrieve_databundle: true  #  Recommended 'true', for the first run. Otherwise data might be missing.
  download_osm_data: true  # If 'true', OpenStreetMap data will be downloaded for the above given countries
  build_natura_raster: true  # If True, than an exclusion raster will be build
  build_cutout: false
  # If "build_cutout" : true, then environmental data is extracted according to `snapshots` date range and `countries`
  # requires cds API key https://cds.climate.copernicus.eu/api-how-to
  # More information https://atlite.readthedocs.io/en/latest/introduction.html#datasets

# download_osm_data_nprocesses: 10  # (optional) number of threads used to download osm data

augmented_line_connection:
  add_to_snakefile: True  # If True, includes this rule to the workflow
  connectivity_upgrade: 3  # Min. lines connection per node, https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.connectivity.edge_augmentation.k_edge_augmentation.html#networkx.algorithms.connectivity.edge_augmentation.k_edge_augmentation
  new_line_type: "HVDC"  # Expanded lines can be either "HVAC" or "HVDC"
  min_expansion: 1  # New created line expands by float/int input [MW]

cluster_options:
  alternative_clustering: False  # Cluster on "False" GADM shapes, "True" Voronoi cells
  distribute_cluster: ['load'] # Distributes cluster nodes per country according to ['load'],['pop'] or ['gdp']
  out_logging: True  # When "True", logging is printed to console

build_shape_options:
    gadm_layer_id: 1  # GADM level area used for the gadm_shapes. Codes are country-dependent but roughly: 0: country, 1: region/county-like, 2: municipality-like
    update_file: False  # When true, all the input files are downloaded again and replace the existing files
    out_logging: True  # When true, logging is printed to console
    year: 2020  # reference year used to derive shapes, info on population and info on GDP
    nprocesses: 5  # number of processes to be used in build_shapes

clean_osm_data_options:  # osm = OpenStreetMap
  names_by_shapes: True  # Set the country name based on the extended country shapes
  threshold_voltage: 35000  # [V] assets below that voltage threshold will not be used (cable, line, generator, etc.)
  tag_substation: "transmission"  # Filters only substations with 'transmission' tag, ('distribution' also available)
  add_line_endings: True  # When "True", then line endings are added to the dataset of the substations
  group_close_buses: True  # When "True", close buses are merged and guarantee the voltage matching among line endings

base_network:
  min_voltage_substation_offshore: 35000  # [V] minimum voltage of the offshore substations
  min_voltage_rebase_voltage: 35000  # [V] minimum voltage in base network

load_options:
  weather_year: 2014  # Not active, but load scenarios available with different weather year (different renewable potentials)
  prediction_year: 2030  # Not active, but load scenarios available with different prediction year (GDP, population)
  scale: 1  # scales all load time-series, i.e. 2 = doubles load


electricity:
  voltages: [220., 300., 380.]
  co2limit: 7.75e+7  # European default, 0.05 * 3.1e9*0.5, needs to be adjusted for Africa
  co2base: 1.487e9  # European default, adjustment to Africa necessary
  agg_p_nom_limits: data/agg_p_nom_minmax.csv

  extendable_carriers:
    Generator: []
    StorageUnit: []
    Store: [battery, H2]
    Link: []

  conventional_carriers: ["OCGT", "CCGT", "oil"]

  max_hours:
    battery: 6
    H2: 168

  powerplants_filter:

lines:
  types:
    220.: "Al/St 240/40 2-bundle 220.0"
    300.: "Al/St 240/40 3-bundle 300.0"
    380.: "Al/St 240/40 4-bundle 380.0"
  s_max_pu: 0.7
  s_nom_max: .inf
  length_factor: 1.25
  under_construction: "zero" # 'zero': set capacity to zero, 'remove': remove, 'keep': with full capacity

links:
  p_max_pu: 1.0
  p_nom_max: .inf
  include_tyndp: true
  under_construction: "zero" # 'zero': set capacity to zero, 'remove': remove, 'keep': with full capacity

transformers:
  x: 0.1
  s_nom: 2000.
  type: ""

atlite:
  nprocesses: 4
  cutouts:
    # geographical bounds automatically determined from countries input
    africa-2013-era5:
      module: era5
      dx: 0.3  # cutout resolution
      dy: 0.3  # cutout resolution
      time: ["2013", "2013"]  # cutout weather year (~40 years available)


renewable:
  onwind:
    cutout: africa-2013-era5
    resource:
      method: wind
      turbine: Vestas_V112_3MW
    capacity_per_sqkm: 3 # conservative, ScholzPhd Tab 4.3.1: 10MW/km^2
    # correction_factor: 0.93
    copernicus:
      grid_codes: [20,30,40,60,100,111,112,113,114,115,116,121,122,123,124,125,126] # maybe also: 0
      distance_to_grid_codes: [50]
      distance: 1000
    # Scholz, Y. (2012). Renewable energy based electricity supply at low costs:
    #  development of the REMix model and application for Europe. ( p.42 / p.28)
    # grid_codes are explained in the data/bundle/corine/legend/clc_legend.xlsx file
    corine:
      grid_codes: [
        12   , # CLC_CODE: 211 (Agricultural areas->Arable land->Non-irrigated arable land)
        13   , # CLC_CODE: 212 (Agricultural areas->Arable land->Permanently irrigated land)
        14   , # CLC_CODE: 213 (Agricultural areas->Arable land->Rice fields)
        15   , # CLC_CODE: 221 (Agricultural areas->Permanent crops->Vineyards)
        16   , # CLC_CODE: 222 (Agricultural areas->Permanent crops->Fruit trees and berry plantations)
        17   , # CLC_CODE: 223 (Agricultural areas->Permanent crops->Olive groves)
        18   , # CLC_CODE: 231 (Agricultural areas->Pastures->Pastures)
        19   , # CLC_CODE: 241 (Agricultural areas->Heterogeneous agricultural areas->Annual crops associated with permanent crops)
        20   , # CLC_CODE: 242 (Agricultural areas->Heterogeneous agricultural areas->Complex cultivation patterns)
        21   , # CLC_CODE: 243 (Agricultural areas->Heterogeneous agricultural areas->Land principally occupied by agriculture, with significant areas of natural vegetation)
        22   , # CLC_CODE: 244 (Agricultural areas->Heterogeneous agricultural areas->Agro-forestry areas)
        23   , # CLC_CODE: 311 (Forest and semi natural areas->Forests->Broad-leaved forest)
        24   , # CLC_CODE: 312 (Forest and semi natural areas->Forests->Coniferous forest)
        25   , # CLC_CODE: 313 (Forest and semi natural areas->Forests->Mixed forest)
        26   , # CLC_CODE: 321 (Forest and semi natural areas->Scrub and/or herbaceous vegetation associations->Natural grasslands)
        27   , # CLC_CODE: 322 (Forest and semi natural areas->Scrub and/or herbaceous vegetation associations->Moors and heathland)
        28   , # CLC_CODE: 323 (Forest and semi natural areas->Scrub and/or herbaceous vegetation associations->Sclerophyllous vegetation)
        29   , # CLC_CODE: 324 (Forest and semi natural areas->Scrub and/or herbaceous vegetation associations->Transitional woodland-shrub)
        31   , # CLC_CODE: 332 (Forest and semi natural areas->Open spaces with little or no vegetation->Bare rocks)
        32   , # CLC_CODE: 333 (Forest and semi natural areas->Open spaces with little or no vegetation->Sparsely vegetated areas)
      ]
      # Distance in m to keep from <distance_grid_codes>
      distance: 1000
      # CLC grid_codes from which to keep the distance
      distance_grid_codes: [
        1   , # CLC_CODE: 111 (Artificial surfaces->Urban fabric->Continuous urban fabric)
        2   , # CLC_CODE: 112 (Artificial surfaces->Urban fabric->Discontinuous urban fabric)
        3   , # CLC_CODE: 121 (Artificial surfaces->Industrial, commercial and transport units->Industrial or commercial units)
        4   , # CLC_CODE: 122 (Artificial surfaces->Industrial, commercial and transport units->Road and rail networks and associated land)
        5   , # CLC_CODE: 123 (Artificial surfaces->Industrial, commercial and transport units->Port areas)
        6   , # CLC_CODE: 124 (Artificial surfaces->Industrial, commercial and transport units->Airports)
      ]
     natura: true
     potential: simple # or conservative
     clip_p_max_pu: 1.e-2
     extendable: true
   offwind-ac:
     cutout: africa-2013-era5
    resource:
      method: wind
      turbine: NREL_ReferenceTurbine_5MW_offshore
    capacity_per_sqkm: 2
    # correction_factor: 0.93
    copernicus:
      grid_codes: [200] # maybe also: 0
    corine: [
      44   , # CLC_CODE: 523 (Water bodies->Marine waters->Sea and ocean)
      255  , # CLC_CODE: 990 (UNCLASSIFIED->UNCLASSIFIED->UNCLASSIFIED)
    ]
    natura: true
    max_depth: 50
    max_shore_distance: 30000
    potential: simple # or conservative
    clip_p_max_pu: 1.e-2
    extendable: true
  offwind-dc:
    cutout: africa-2013-era5
    resource:
      method: wind
      turbine: NREL_ReferenceTurbine_5MW_offshore
    # ScholzPhd Tab 4.3.1: 10MW/km^2
    capacity_per_sqkm: 3
    # correction_factor: 0.93
    copernicus:
      grid_codes: [200] # maybe also: 0
    corine: [
      44   , # CLC_CODE: 523 (Water bodies->Marine waters->Sea and ocean)
      255  , # CLC_CODE: 990 (UNCLASSIFIED->UNCLASSIFIED->UNCLASSIFIED)
    ]
    natura: true
    max_depth: 50
    min_shore_distance: 30000
    potential: simple # or conservative
    clip_p_max_pu: 1.e-2
    extendable: true
  solar:
    cutout: africa-2013-era5
    resource:
      method: pv
      panel: CSi
      orientation: #TODO: should be latitude optimal
        slope: 35.
        azimuth: 180.
    capacity_per_sqkm: 1.7 # ScholzPhd Tab 4.3.1: 170 MW/km^2
    # Determined by comparing uncorrected area-weighted full-load hours to those
    # published in Supplementary Data to
    # Pietzcker, Robert Carl, et al. "Using the sun to decarbonize the power
    # sector: The economic potential of photovoltaics and concentrating solar
    # power." Applied Energy 135 (2014): 704-720.
    correction_factor: 0.854337
    copernicus:
      grid_codes: [20, 30, 40, 50, 60, 70, 80] # maybe also: 0, 90, 200
    corine: [
      1   , # CLC_CODE: 111 (Artificial surfaces->Urban fabric->Continuous urban fabric)
      2   , # CLC_CODE: 112 (Artificial surfaces->Urban fabric->Discontinuous urban fabric)
      3   , # CLC_CODE: 121 (Artificial surfaces->Industrial, commercial and transport units->Industrial or commercial units)
      4   , # CLC_CODE: 122 (Artificial surfaces->Industrial, commercial and transport units->Road and rail networks and associated land)
      5   , # CLC_CODE: 123 (Artificial surfaces->Industrial, commercial and transport units->Port areas)
      6   , # CLC_CODE: 124 (Artificial surfaces->Industrial, commercial and transport units->Airports)
      7   , # CLC_CODE: 131 (Artificial surfaces->Mine, dump and construction sites->Mineral extraction sites)
      8   , # CLC_CODE: 132 (Artificial surfaces->Mine, dump and construction sites->Dump sites)
      9   , # CLC_CODE: 133 (Artificial surfaces->Mine, dump and construction sites->Construction sites)
      10  , # CLC_CODE: 141 (Artificial surfaces->Artificial, non-agricultural vegetated areas->Green urban areas)
      11  , # CLC_CODE: 142 (Artificial surfaces->Artificial, non-agricultural vegetated areas->Sport and leisure facilities)
      12  , # CLC_CODE: 211 (Agricultural areas->Arable land->Non-irrigated arable land)
      13  , # CLC_CODE: 212 (Agricultural areas->Arable land->Permanently irrigated land)
      14  , # CLC_CODE: 213 (Agricultural areas->Arable land->Rice fields)
      15  , # CLC_CODE: 221 (Agricultural areas->Permanent crops->Vineyards)
      16  , # CLC_CODE: 222 (Agricultural areas->Permanent crops->Fruit trees and berry plantations)
      17  , # CLC_CODE: 223 (Agricultural areas->Permanent crops->Olive groves)
      18  , # CLC_CODE: 231 (Agricultural areas->Pastures->Pastures)
      19  , # CLC_CODE: 241 (Agricultural areas->Heterogeneous agricultural areas->Annual crops associated with permanent crops)
      20  , # CLC_CODE: 242 (Agricultural areas->Heterogeneous agricultural areas->Complex cultivation patterns)
      26  , # CLC_CODE: 321 (Forest and semi natural areas->Scrub and/or herbaceous vegetation associations->Natural grasslands)
      31  , # CLC_CODE: 332 (Forest and semi natural areas->Open spaces with little or no vegetation->Bare rocks)
      32  , # CLC_CODE: 333 (Forest and semi natural areas->Open spaces with little or no vegetation->Sparsely vegetated areas)
    ]
    natura: true
    potential: simple # or conservative
    clip_p_max_pu: 1.e-2
    extendable: true
  hydro:
    cutout: africa-2013-era5
    resource:
      method: hydro
      plants: data/clean/africa_all_substations.geojson
      hydrobasins: data/raw/hydrobasins/hybas_lake_af_lev04_v1c.shp
      # flowspeed: 1.0
      # weight_with_height: false
      # show_progress: true
    carriers: [ror, PHS, hydro]
    PHS_max_hours: 6
    hydro_max_hours: "energy_capacity_totals_by_country"  # not active
    clip_min_inflow: 1.0
    extendable: true

# TODO: Needs to be adjusted for Africa
costs:
  year: 2030
  discountrate: 0.07 # From a Lion Hirth paper, also reflects average of Noothout et al 2016
  USD2013_to_EUR2013: 0.7532 # [EUR/USD] ECB: https://www.ecb.europa.eu/stats/exchange/eurofxref/html/eurofxref-graph-usd.en.html
  marginal_cost: # EUR/MWh
    solar: 0.01
    onwind: 0.015
    offwind: 0.015
    hydro: 0.
    H2: 0.
    electrolysis: 0.
    fuel cell: 0.
    battery: 0.
    battery inverter: 0.
  emission_prices: # in currency per tonne emission, only used with the option Ep
    co2: 0.


solving:
  options:
    formulation: kirchhoff
    load_shedding: true
    noisy_costs: true
    min_iterations: 4
    max_iterations: 6
    clip_p_max_pu: 0.01
    skip_iterations: true
    track_iterations: false
    #nhours: 10
  solver:
    name: gurobi
    threads: 4
    method: 2 # barrier (=ipm)
    crossover: 0
    BarConvTol: 1.e-5
    FeasibilityTol: 1.e-6
    AggFill: 0
    PreDual: 0
    GURO_PAR_BARDENSETHRESH: 200


plotting:
  map:
    figsize: [7, 7]
    boundaries: [-10.2, 29, 35, 72]
    p_nom:
      bus_size_factor: 5.e+4
      linewidth_factor: 3.e+3

  costs_max: 800
  costs_threshold: 1

  energy_max: 15000.
  energy_min: -10000.
  energy_threshold: 50.

  vre_techs: ["onwind", "offwind-ac", "offwind-dc", "solar", "ror"]
  conv_techs: ["OCGT", "CCGT", "Nuclear", "Coal"]
  storage_techs: ["hydro+PHS", "battery", "H2"]
  load_carriers: ["AC load"]
  AC_carriers: ["AC line", "AC transformer"]
  link_carriers: ["DC line", "Converter AC-DC"]
  tech_colors:
    "onwind": "#235ebc"
    "onshore wind": "#235ebc"
    "offwind": "#6895dd"
    "offwind-ac": "#6895dd"
    "offshore wind": "#6895dd"
    "offshore wind ac": "#6895dd"
    "offwind-dc": "#74c6f2"
    "offshore wind dc": "#74c6f2"
    "hydro": "#08ad97"
    "hydro+PHS": "#08ad97"
    "PHS": "#08ad97"
    "hydro reservoir": "#08ad97"
    "hydroelectricity": "#08ad97"
    "ror": "#4adbc8"
    "run of river": "#4adbc8"
    "solar": "#f9d002"
    "solar PV": "#f9d002"
    "solar thermal": "#ffef60"
    "biomass": "#0c6013"
    "solid biomass": "#06540d"
    "biogas": "#23932d"
    "waste": "#68896b"
    "geothermal": "#ba91b1"
    "OCGT": "#d35050"
    "gas": "#d35050"
    "natural gas": "#d35050"
    "CCGT": "#b20101"
    "nuclear": "#ff9000"
    "coal": "#707070"
    "lignite": "#9e5a01"
    "oil": "#262626"
    "H2": "#ea048a"
    "hydrogen storage": "#ea048a"
    "battery": "#b8ea04"
    "Electric load": "#f9d002"
    "electricity": "#f9d002"
    "lines": "#70af1d"
    "transmission lines": "#70af1d"
    "AC-AC": "#70af1d"
    "AC line": "#70af1d"
    "links": "#8a1caf"
    "HVDC links": "#8a1caf"
    "DC-DC": "#8a1caf"
    "DC link": "#8a1caf"
    "load": "#FF0000"
  nice_names:
    OCGT: "Open-Cycle Gas"
    CCGT: "Combined-Cycle Gas"
    offwind-ac: "Offshore Wind (AC)"
    offwind-dc: "Offshore Wind (DC)"
    onwind: "Onshore Wind"
    solar: "Solar"
    PHS: "Pumped Hydro Storage"
    hydro: "Reservoir & Dam"
    battery: "Battery Storage"
    H2: "Hydrogen Storage"
    lines: "Transmission Lines"
    ror: "Run of River"
