library(rasterVis)
library(maptools)
library(mapdata)
library(sf)
library(raster)
library(tidyverse)
library("rnaturalearth")
library("rnaturalearthdata")
library(ggthemes)
# library(rgee)
# library(rgee)
# ee_Initialize()

world <- rnaturalearth::ne_countries(scale = "medium", returnclass = "sf")

water_yg <- raster("D:/OneDrive - IIASA/Current papers/LEAP_RE_position_paper/irr_demand_to_closeYgap_m3.txt")
crs(water_yg) <- "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"

water_yg <- rgis::mask_raster_to_polygon(water_yg, world %>% filter(region_wb=="Sub-Saharan Africa"))

water_yg <- as.data.frame(water_yg, xy=T)

library(gtools)

water_yg$irr_demand_to_closeYgap_m3_cut <- cut(water_yg$irr_demand_to_closeYgap_m3/1e6, round(quantile(water_yg$irr_demand_to_closeYgap_m3/1e6, c(1:5)/5 ,na.rm=T), 1))

a <- ggplot()+
  geom_tile(data = water_yg,
            aes(x = x, y = y, fill = irr_demand_to_closeYgap_m3_cut)) +
  scale_fill_brewer("Irrigation needs /nto close the yield gap /n(million m3)", palette = "YlGnBu", na.value = NA)+
  geom_sf(data=world, fill=NA, size =.3)+
  theme_classic()+
  coord_sf(ylim=c(-34, 36), xlim=c(-20, 51))+
  theme(legend.position = c(0.2, 0.32), legend.direction = "vertical", axis.line=element_blank(),axis.text.x=element_blank(), legend.title=element_text(size=8, face = "bold"), panel.border = element_rect(colour = "black", fill=NA, size=1),
        axis.text.y=element_blank(),axis.ticks=element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank())+
  guides(fill = guide_colorsteps(barwidth = 1, barheight = 5))+
  xlab("")+
  ylab("")+
  ggtitle("A")

#pop. without electricity
popnoaccess_df <- stack("D:/Electrification_SSA_data/dataset/noaccess_SSA_2014_2020.nc")[[7]]

popnoaccess_df <- aggregate(popnoaccess_df, fact=25, fun="sum", na.rm=T)

popnoaccess <- as.data.frame(popnoaccess_df, xy=T)

# values(popnoaccess_df2) <- ifelse(values(popnoaccess_df2)>10000, 1, NA)

popnoaccess$X7 <- ifelse(popnoaccess$X7/625 < 2.5, NA, popnoaccess$X7)

popnoaccess$X7_cut <- cut(popnoaccess$X7/625, c(5, 10, 50, 250, 1000, 1500))

b <- ggplot()+
  geom_tile(data = popnoaccess,
            aes(x = x, y = y, fill = X7_cut)) +
  scale_fill_brewer("Density of population /nwithout electricity /n(people / sq. km)", palette = "YlOrRd", na.value = NA)+
  geom_sf(data=world, fill=NA, size =.3)+
  theme_classic()+
  coord_sf(ylim=c(-34, 36), xlim=c(-20, 51))+
  theme(legend.position = c(0.2, 0.32), legend.direction = "vertical", axis.line=element_blank(),axis.text.x=element_blank(), legend.title=element_text(size=8, face = "bold"), panel.border = element_rect(colour = "black", fill=NA, size=1),
        axis.text.y=element_blank(),axis.ticks=element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank())+
  guides(fill = guide_colorsteps(barwidth = 1, barheight = 5))+
  xlab("")+
  ylab("")+
  ggtitle("B")

#

cleanwat <- raster("D:/OneDrive - IIASA/Current papers/LEAP_RE_position_paper/clean_water_need.nc")

cleanwat <- rgis::mask_raster_to_polygon(cleanwat, world %>% filter(region_wb=="Sub-Saharan Africa"))

cleanwat <- as.data.frame(cleanwat, xy=T)

cleanwat$layer_cut <- cut(cleanwat$layer, c(5, 10, 50, 250, 1000, 1500))

c <- ggplot()+
  geom_tile(data = cleanwat,
            aes(x = x, y = y, fill = layer_cut)) +
  scale_fill_brewer("Density of population /nwithout clean water /n(people / sq. km)", palette = "PuBu", na.value = NA)+
  geom_sf(data=world, fill=NA, size =.3)+
  theme_classic()+
  coord_sf(ylim=c(-34, 36), xlim=c(-20, 51))+
  theme(legend.position = c(0.2, 0.32), legend.direction = "vertical", axis.line=element_blank(),axis.text.x=element_blank(), legend.title=element_text(size=8, face = "bold"), panel.border = element_rect(colour = "black", fill=NA, size=1),
        axis.text.y=element_blank(),axis.ticks=element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank())+
  guides(fill = guide_colorsteps(barwidth = 1, barheight = 5))+
  xlab("")+
  ylab("")+
  ggtitle("C")

sanitation <- raster("D:/OneDrive - IIASA/Current papers/LEAP_RE_position_paper/sanitation_need.nc")

sanitation <- rgis::mask_raster_to_polygon(sanitation, world %>% filter(region_wb=="Sub-Saharan Africa"))

sanitation <- as.data.frame(sanitation, xy=T)

sanitation$layer_cut <- cut(sanitation$layer, c(5, 10, 50, 250, 1000, 1500))

d <- ggplot()+
  geom_tile(data = sanitation,
            aes(x = x, y = y, fill = layer_cut)) +
  scale_fill_brewer("Density of population /nwithout sanitation /n(people / sq. km)", palette = "PuRd", na.value = NA)+
  geom_sf(data=world, fill=NA, size =.3)+
  theme_classic()+
  coord_sf(ylim=c(-34, 36), xlim=c(-20, 51))+
  theme(legend.position = c(0.2, 0.32), legend.direction = "vertical", axis.line=element_blank(),axis.text.x=element_blank(), legend.title=element_text(size=8, face = "bold"), panel.border = element_rect(colour = "black", fill=NA, size=1),
        axis.text.y=element_blank(),axis.ticks=element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank())+
  guides(fill = guide_colorsteps(barwidth = 1, barheight = 5))+
  xlab("")+
  ylab("")+
  ggtitle("D")

all <- cowplot::plot_grid(a, b, c, d, ncol=2)

ggsave("D:/OneDrive - IIASA/Current papers/LEAP_RE_position_paper/maps.pdf", all, device="pdf", width = 9, height = 9)

ggsave("D:/OneDrive - IIASA/Current papers/LEAP_RE_position_paper/maps.png", all, device="png", width = 9, height = 9)


###

# UR/RUR

world <- rnaturalearth::ne_countries(scale = "medium", returnclass = "sf")

water_yg <- raster("D:/OneDrive - IIASA/Current papers/LEAP_RE_position_paper/irr_demand_to_closeYgap_m3.txt")
crs(water_yg) <- "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"

water_yg <- rgis::mask_raster_to_polygon(water_yg, world %>% filter(region_wb=="Sub-Saharan Africa"))

popnoaccess_df <- stack("D:/Electrification_SSA_data/dataset/noaccess_SSA_2014_2020.nc")[[7]]

popnoaccess_df <- aggregate(popnoaccess_df, fact=25, fun="sum", na.rm=T)

cleanwat <- raster("D:/OneDrive - IIASA/Current papers/LEAP_RE_position_paper/clean_water_need.nc")

cleanwat <- rgis::mask_raster_to_polygon(cleanwat, world %>% filter(region_wb=="Sub-Saharan Africa"))

sanitation <- raster("D:/OneDrive - IIASA/Current papers/LEAP_RE_position_paper/sanitation_need.nc")

sanitation <- rgis::mask_raster_to_polygon(sanitation, world %>% filter(region_wb=="Sub-Saharan Africa"))

#

rm(list=ls()[! ls() %in% c("water_yg","popnoaccess_df", "cleanwat")])
gc()

world <- rnaturalearth::ne_countries(scale = "medium", returnclass = "sf")

m <- raster("D:/OneDrive - IIASA/Archivio/Su-Min/Data for TIMER integration/ghs_layer_smod_2015.tif")
m <- projectRaster(m, cleanwat, method = "ngb")
m <- rgis::mask_raster_to_polygon(m, world %>% filter(region_wb=="Sub-Saharan Africa"))
m[m > 20] <- NA

sanitation <- projectRaster(sanitation, m)
popnoaccess_df <- projectRaster(popnoaccess_df, m)
cleanwat <- projectRaster(cleanwat, m)

sanitation <- mask(sanitation, m)
popnoaccess_df <- mask(popnoaccess_df, m)
cleanwat <- mask(cleanwat, m)

#

sanitation <- sanitation>quantile(values(sanitation), .5, na.rm=T)
popnoaccess_df <- popnoaccess_df>quantile(values(popnoaccess_df), .5, na.rm=T)
cleanwat <- cleanwat>quantile(values(cleanwat), .5, na.rm=T)

rm(list=ls()[! ls() %in% c("sanitation","popnoaccess_df", "cleanwat")])
gc()

sanitation_df <- as.data.frame(sanitation_df, xy=T)
popnoaccess_df_df <- as.data.frame(popnoaccess_df, xy=T)
cleanwat_df <- as.data.frame(cleanwat, xy=T)

merger <- Reduce(function(x,y) merge(x,y,by=c("x", "y"),all=TRUE) ,list(sanitation_df,popnoaccess_df_df,cleanwat_df))

world <- rnaturalearth::ne_countries(scale = "medium", returnclass = "sf")

merger$value <- ifelse((merger$layer.x == 1 & merger$layer.y ==1 & merger$layer == 1), 1, NA)

boxes1<-data.frame(maxlat = 14,minlat = 4,maxlong = 14,minlong = 4, id="1")
boxes2<-data.frame(maxlat = 16,minlat = 10,maxlong = 40,minlong = 21, id="1")
boxes3<-data.frame(maxlat = -10,minlat = -20,maxlong =42 ,minlong = 21, id="1")

#

rainfed <- raster("D:/OneDrive - IIASA/Current papers/LEAP_RE_position_paper/GFSAD1KCM.2010.001.2016348142550.tif")

rainfed<- rgis::mask_raster_to_polygon(rainfed, world %>% filter(region_wb=="Sub-Saharan Africa"))

rainfed <- as.data.frame(rainfed, xy=T)

rainfed$GFSAD1KCM.2010.001.2016348142550 <- ifelse(rainfed$GFSAD1KCM.2010.001.2016348142550==3 | rainfed$GFSAD1KCM.2010.001.2016348142550==4 rainfed$GFSAD1KCM.2010.001.2016348142550==5 |, 1, NA)

rainfed <- na.exclude(rainfed)

#

e <- ggplot()+
  geom_tile(data = rainfed,
            aes(x = x, y = y), fill="forestgreen", alpha=0.5) +
  geom_tile(data = merger,
            aes(x = x, y = y, fill = as.factor(value)), alpha=0.75) +
  scale_fill_discrete(na.value = NA)+
  geom_sf(data=world, fill=NA, size =.3)+
  theme_classic()+
  coord_sf(ylim=c(-34, 36), xlim=c(-20, 51))+
  theme(legend.position = "none", legend.direction = "vertical", axis.line=element_blank(),axis.text.x=element_blank(), legend.title=element_text(size=8, face = "bold"), panel.border = element_rect(colour = "black", fill=NA, size=1),
        axis.text.y=element_blank(),axis.ticks=element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank())+
  #guides(fill = guide_colorsteps(barwidth = 1, barheight = 5))+
  xlab("")+
  ylab("")
  # geom_rect(data=boxes1, aes(xmin=minlong , xmax=maxlong, ymin=minlat, ymax=maxlat ), color="blue", size=.7, fill="transparent") + geom_rect(data=boxes2, aes(xmin=minlong , xmax=maxlong, ymin=minlat, ymax=maxlat ), color="blue", size=.7, fill="transparent")  + geom_rect(data=boxes3, aes(xmin=minlong , xmax=maxlong, ymin=minlat, ymax=maxlat ), color="blue", size=.7, fill="transparent")

#ggsave("D:/OneDrive - IIASA/Current papers/LEAP_RE_position_paper/maps_hotspot.pdf", e, device="pdf")

ggsave("D:/OneDrive - IIASA/Current papers/LEAP_RE_position_paper/maps_hotspot.png", e, device="png", width = 4.5, height = 4.5, dpi=450)
