# SPDX-FileCopyrightText: : 2017-2020 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: pypsa-africa
channels:
- conda-forge
- bioconda
- gurobi
dependencies:
- python>=3.8
- pip
- mamba   # esp for windows build

# - pypsa>=0.17.1
# - atlite>=0.2.4  # until https://github.com/PyPSA/atlite/issues/244 is not merged
- dask
  # - powerplantmatching>=0.4.8

  # Dependencies of the workflow itself
- xlrd
- openpyxl
- pycountry
- seaborn
- snakemake-minimal
- memory_profiler
- yaml
- pytables
- lxml
- numpy
- pandas
- geopandas
- fiona<=1.8.20  # Till issue https://github.com/Toblerity/Fiona/issues/1085 is not solved
- xarray
- netcdf4
- networkx
- scipy
- shapely>=1.8a1
- pre-commit
- pyomo
- matplotlib
- reverse-geocode

  # Keep in conda environment when calling ipython
- ipython
  # Jupyter notebook requirement
- ipykernel
- jupyterlab

  # GIS dependencies:
- cartopy
- descartes
- rasterio<1.2.10  # until atlite is up to date https://github.com/PyPSA/atlite/issues/238
- rioxarray

 # Plotting
- geoviews
- hvplot
- graphviz
- contextily
- graphviz

  # PyPSA-Eur-Sec Dependencies
- geopy
- tqdm
- pytz
- country_converter

  # Cloud download
# - googledrivedownloader  # Commented until https://github.com/ndrplz/google-drive-downloader/pull/28 is merged: PR installed using pip

# Default solver for tests (moved to the CI)
# - glpk
- coincbc
- ipopt < 3.13.3
- gurobi

- pip:
  # - git+https://github.com/pypsa/pypsa.git#egg=pypsa
  - git+https://github.com/davide-f/powerplantmatching.git@new_pypsa_africa#egg=powerplantmatching
  - git+https://github.com/davide-f/google-drive-downloader@master  # google drive with fix for virus scan
  - git+https://github.com/davide-f/atlite.git@master
  - git+https://github.com/ekatef/PyPSA.git@master
  - vresutils>=0.3.1
  - tsam>=1.1.0
  - esy-osm-pbf
  - esy-osmfilter
