# SPDX-FileCopyrightText: : 2021 The PyPSA-Africa Authors
#
# SPDX-License-Identifier: CC0-1.0

# File describing the data bundle configurations that can be downloaded
# by using the retrieve_databundle fule

# Each bundle shall have the following structure:

# .. code:: yaml

#   bundle_name:  # name of the bundle
#     countries: [country code, region code or country list]  # list of countries represented in the databundle
#     [tutorial: true/false]  # (optional, default false) whether the bundle is a tutorial or not
#     category: common/resources/data/cutouts  # category of data contained in the bundle:
#     destination: "."  # folder where to unzip the files with respect to the repository root (\"\" or \".\")
#     urls:  # list of urls by source, e.g. zenodo or google
#       zenodo: {zenodo url}
#       google: {google url}


# tutorial bundle specific for Nigeria and Benin only
bundle_data_tutorial:
  countries: [NG, BJ]
  tutorial: true
  category: data
  destination: "data"
  urls:
    zenodo: https://sandbox.zenodo.org/record/1016522/files/tutorial_data.zip?download=1
    google: https://drive.google.com/file/d/1Yd2iM892WFBRxh5NX22if6laRF1RxZKu/view?usp=sharing

# tutorial bundle specific for Nigeria and Benin only
bundle_resources_tutorial:
  countries: [NG, BJ]
  tutorial: true
  category: resources
  destination: "resources"
  urls:
    zenodo: https://sandbox.zenodo.org/record/1016001/files/tutorial_resources.zip?download=1
    google: https://drive.google.com/file/d/1WWVyXHA2E7aGcg_OC1lN8Pb2tA8DgfU0/view?usp=sharing

# tutorial bundle specific for Nigeria and Benin only
bundle_cutouts_tutorial:
  countries: [NG, BJ]
  tutorial: true
  category: cutouts
  destination: "cutouts"
  urls:
    zenodo: https://sandbox.zenodo.org/record/1016015/files/tutorial_cutouts.zip?download=1
    google: https://drive.google.com/file/d/1Lro4X92sVuD30C0B3sQ2jJU37uZ50DWi/view?usp=sharing

# data bundle containing the data of the data folder common to all regions of the world
bundle_data_world:
  countries: [world]
  category: common
  destination: "data"
  urls:
    zenodo: https://sandbox.zenodo.org/record/1016540/files/common_data.zip?download=1
    google: https://drive.google.com/file/d/1fo-YsyU2LKkVeg5Ea0JbcEx-zQ3kJKW7/view?usp=sharing

# resources bundle containing the resources folder for africa only
bundle_resources_world:
  countries: [world]
  category: resources
  destination: "resources"
  urls:
    zenodo: https://sandbox.zenodo.org/record/1016878/files/resources_africa.zip?download=1
    google: https://drive.google.com/file/d/1abwx1FviogYUsnP27MrCzQf-3w-9IHDl/view?usp=sharing

# data bundle of the data folder for the african continent
bundle_landcover_africa:
  countries: [africa]
  category: landcover
  destination: "data/raw/landcover"
  urls:
    zenodo: https://sandbox.zenodo.org/record/1016042/files/landcover_africa.zip?download=1
    google: https://drive.google.com/file/d/1l6Xgr3PXyvgqWaXUbto9zvvMS_OgSjvG/view?usp=sharing

# data bundle of the data folder for the african continent
bundle_landcover_asiapacific:
  countries: [asia, australia-oceania]
  category: landcover
  destination: "data/raw/landcover"
  urls:
    zenodo: https://sandbox.zenodo.org/record/1016042/files/landcover_asiapacific.zip?download=1
    google: https://drive.google.com/file/d/1-bevGdoAltJ1useZAS9PqEMDJQLyBEn8/view?usp=sharing

# data bundle of the data folder for the african continent
bundle_landcover_latinamerica_caribbean:
  countries: [latin_america, central_america]
  category: landcover
  destination: "data/raw/landcover"
  urls:
    zenodo: https://sandbox.zenodo.org/record/1016042/files/landcover_latinamerica_caribbean.zip?download=1
    google: https://drive.google.com/file/d/16GiEqdUcX0juGHaAxk5q9XlgUl2T7eVf/view?usp=sharing

# data bundle of the data folder for the african continent
bundle_landcover_westasia:
  countries: [WAS]
  category: landcover
  destination: "data/raw/landcover"
  urls:
    zenodo: https://sandbox.zenodo.org/record/1016042/files/landcover_westasia.zip?download=1
    google: https://drive.google.com/file/d/1QDFn-USxTEToFrST8Iazj9Cz_mcXEwiP/view?usp=sharing

# data bundle of the data folder for europe
bundle_landcover_europe:
  countries: [europe]
  category: landcover
  destination: "data/raw/landcover"
  urls:
    zenodo: https://sandbox.zenodo.org/record/1018640/files/landcover_europe.zip?download=1
    google: https://drive.google.com/file/d/1zQuKnZFp6ASYD_e-dbWbWXYg330E0occ/view?usp=sharing

# data bundle of the data folder for the poles
bundle_landcover_northamerica:
  countries: [north_america]  # Greenland and antartica
  category: landcover
  destination: "data/raw/landcover"
  urls:
    zenodo: https://sandbox.zenodo.org/record/1018640/files/landcover_northamerica.zip?download=1
    google: https://drive.google.com/file/d/1gu7PH08ZEpL4cBQa_fMUSq2m6LY1_UJo/view?usp=sharing

# data bundle of the data folder for the poles
bundle_landcover_poles:
  countries: [GL, ATA]  # Greenland and antartica
  category: landcover
  destination: "data/raw/landcover"
  urls:
    zenodo: https://sandbox.zenodo.org/record/1018640/files/landcover_polar.zip?download=1
    google: https://drive.google.com/file/d/1cUDcE6wpQVZNf3K9ffV6pNXfxq6sA65E/view?usp=sharing

# cutouts bundle of the cutouts folder for the african continent
bundle_cutouts_africa:
  countries: [africa]
  category: cutouts
  destination: "cutouts"
  urls:
    zenodo: https://sandbox.zenodo.org/record/1016042/files/cutouts_africa.zip?download=1
    google: https://drive.google.com/file/d/1-Njs7BqG0YE5QwBHj0zgkdicb5IQvQCh/view
